Update deploy-pipeline.yml

diff --git a/.github/workflows/deploy-pipeline.yml b/.github/workflows/deploy-pipeline.yml
--- a/.github/workflows/deploy-pipeline.yml
+++ b/.github/workflows/deploy-pipeline.yml
@@ -35,26 +35,26 @@ jobs:
     strategy:
       matrix:
         python-version: [3.8]
-  name: Build and deploy the pipeline
+    name: Build and deploy the pipeline
     env:
       AWS_ACCOUNT_ID: ${{ inputs.awsAccountId || secrets.AWS_ACCOUNT_ID }}
       AWS_REGION: ${{ inputs.awsRegion || secrets.AWS_REGION }}
       CLIENT_CODE: ${{ inputs.clientCode || secrets.CLIENT_CODE }}
       DATATEER_ENV: ${{ inputs.environment || "int" }}
-  steps:
-    - name: Prerequisites
-      run: |
-        [ -n {{ env.AWS_ACCOUNT_ID }} ] || echo "Could not find AWS_ACCOUNT_ID" && exit 1
-        [ -n {{ env.AWS_REGION }} ] || echo "Could not find AWS_REGION" && exit 1
-        [ -n {{ env.CLIENT_CODE}} ] || echo "Could not find CLIENT_CODE" && exit 1
-        [ -n {{ env.DATATEER_ENV }} ] || echo "Could not find DATATEER_ENV" && exit 1
-        python -m pip install --upgrade pip
+    steps:
+      - name: Prerequisites
+        run: |
+          [ -n {{ env.AWS_ACCOUNT_ID }} ] || echo "Could not find AWS_ACCOUNT_ID" && exit 1
+          [ -n {{ env.AWS_REGION }} ] || echo "Could not find AWS_REGION" && exit 1
+          [ -n {{ env.CLIENT_CODE}} ] || echo "Could not find CLIENT_CODE" && exit 1
+          [ -n {{ env.DATATEER_ENV }} ] || echo "Could not find DATATEER_ENV" && exit 1
+          python -m pip install --upgrade pip
 
-        [ -n {{ inputs.datateerCliVersion }} ]
-        then
-          pip install datateer-cli=={{ inputs.datateerCliVersion }}]
-        else
-          pip install datateer-cli
-        fi
-    - name: Checkout {{ env.CLIENT_CODE }}-pipeline
-      uses: actions/checkout@v2	
+          [ -n {{ inputs.datateerCliVersion }} ]
+          then
+            pip install datateer-cli=={{ inputs.datateerCliVersion }}]
+          else
+            pip install datateer-cli
+          fi
+      - name: Checkout {{ env.CLIENT_CODE }}-pipeline
+        uses: actions/checkout@v2	
