Revert "Merge pull request #3 from Datateer/fix-env-vars"
This reverts commit 42d309760fd7ecaa0e0db42f34f151bffdc35a9f, reversing
changes made to ad71f5b704a6e6721f0cc3f0554c964f3deed642.

diff --git a/.github/workflows/deploy-pipeline-gcp.yml b/.github/workflows/deploy-pipeline-gcp.yml
--- a/.github/workflows/deploy-pipeline-gcp.yml
+++ b/.github/workflows/deploy-pipeline-gcp.yml
@@ -42,7 +42,7 @@ on:
       deployGoogleCredentials:
         description: The google service account credentials JSON used to authenticate with GCP
         required: true
-
+        
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -51,21 +51,21 @@ jobs:
         python-version: [3.8]
     name: Build and deploy the pipeline
     env:
-      ACCOUNT: ${{ inputs.gcpProjectId || secrets.GCP_PROJECT_ID }}
-      REGION: ${{ inputs.gcpRegion || secrets.GCP_REGION }}
+      GCP_PROJECT_ID: ${{ inputs.gcpProjectId || secrets.GCP_PROJECT_ID }}
+      GCP_REGION: ${{ inputs.gcpRegion || secrets.GCP_REGION }}
       CLIENT_CODE: ${{ inputs.clientCode || secrets.CLIENT_CODE }}
       DATATEER_ENV: ${{ inputs.environment || 'int' }}
       PIPELINE_NAME: ${{ inputs.pipeline_name || 'main' }}
     steps:
       - name: Prerequisites
         run: |
-          [ -n "${{ env.ACCOUNT }}" ] || (echo "Could not find ACCOUNT in the inputs or in environment variables" && exit 1)
-          [ -n "${{ env.REGION }}" ] || (echo "Could not find REGION in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.GCP_PROJECT_ID }}" ] || (echo "Could not find GCP_PROJECT_ID in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.GCP_REGION }}" ] || (echo "Could not find GCP_REGION in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.CLIENT_CODE}}" ] || (echo "Could not find CLIENT_CODE in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.DATATEER_ENV }}" ] || (echo "Could not find DATATEER_ENV in the inputs or in environment variables" && exit 1)
-
+          
           python -m pip install --upgrade pip
-
+          
           sudo apt-get install graphviz graphviz-dev
           if [ -n "${{ inputs.datateerCliVersion }}" ]
           then
@@ -73,7 +73,7 @@ jobs:
           else
             pip install datateer-cli
           fi
-
+        
       # This has a serious limitation that makes it difficult to use beyond a single SSH key. Ref https://github.com/webfactory/ssh-agent#using-multiple-keys
       - name: Setup SSH
         uses: webfactory/ssh-agent@v0.4.1
@@ -90,18 +90,18 @@ jobs:
           ./.datateer/build_scripts/pre-build.sh
           pip install .
 
-      - id: "auth"
-        name: "Authenticate to Google Cloud"
-        uses: "google-github-actions/auth@v0"
+      - id: 'auth'
+        name: 'Authenticate to Google Cloud'
+        uses: 'google-github-actions/auth@v0'
         with:
           token_format: "access_token"
-          credentials_json: "${{ secrets.deployGoogleCredentials }}"
+          credentials_json: '${{ secrets.deployGoogleCredentials }}'
 
-      - uses: "docker/login-action@v1"
+      - uses: 'docker/login-action@v1'
         with:
-          registry: "us-central1-docker.pkg.dev" # or REGION-docker.pkg.dev
-          username: "oauth2accesstoken"
-          password: "${{ steps.auth.outputs.access_token }}"
+          registry: 'us-central1-docker.pkg.dev' # or REGION-docker.pkg.dev
+          username: 'oauth2accesstoken'
+          password: '${{ steps.auth.outputs.access_token }}'
 
       - name: Pull down config settings files
         run: datateer config pull --environment ${{ env.DATATEER_ENV }} --cloud gcp --region us-central1 --config-bucket temp-config-bucket
@@ -118,7 +118,7 @@ jobs:
             datateer-docker-pipeline-
 
       - name: Deploy pipeline
-        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud gcp --region ${{ env.REGION }} --account ${{ env.ACCOUNT }}
+        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud gcp --region ${{ env.GCP_REGION }} --account ${{ env.GCP_PROJECT_ID }}
         env:
           DEPLOY_KEY_PREFECT_LIB: ${{ secrets.deployKeyPrefectLib }}
           PREFECT__CLOUD__API_KEY: ${{ secrets.deployKeyPrefect }}
