Fix env vars (#4)
* Revert "Merge pull request #3 from Datateer/fix-env-vars"

This reverts commit 42d309760fd7ecaa0e0db42f34f151bffdc35a9f, reversing
changes made to ad71f5b704a6e6721f0cc3f0554c964f3deed642.

* Fix deployment params

diff --git a/.github/workflows/deploy-pipeline-aws.yml b/.github/workflows/deploy-pipeline-aws.yml
--- a/.github/workflows/deploy-pipeline-aws.yml
+++ b/.github/workflows/deploy-pipeline-aws.yml
@@ -54,16 +54,16 @@ jobs:
         python-version: [3.8]
     name: Build and deploy the pipeline
     env:
-      ACCOUNT: ${{ inputs.awsAccountId || secrets.AWS_ACCOUNT_ID }}
-      REGION: ${{ inputs.awsRegion || secrets.AWS_REGION }}
+      AWS_ACCOUNT_ID: ${{ inputs.awsAccountId || secrets.AWS_ACCOUNT_ID }}
+      AWS_REGION: ${{ inputs.awsRegion || secrets.AWS_REGION }}
       CLIENT_CODE: ${{ inputs.clientCode || secrets.CLIENT_CODE }}
       DATATEER_ENV: ${{ inputs.environment || 'int' }}
       PIPELINE_NAME: ${{ inputs.pipeline_name || 'main' }}
     steps:
       - name: Prerequisites
         run: |
-          [ -n "${{ env.ACCOUNT }}" ] || (echo "Could not find ACCOUNT in the inputs or in environment variables" && exit 1)
-          [ -n "${{ env.REGION }}" ] || (echo "Could not find REGION in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.AWS_ACCOUNT_ID }}" ] || (echo "Could not find AWS_ACCOUNT_ID in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.AWS_REGION }}" ] || (echo "Could not find AWS_REGION in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.CLIENT_CODE}}" ] || (echo "Could not find CLIENT_CODE in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.DATATEER_ENV }}" ] || (echo "Could not find DATATEER_ENV in the inputs or in environment variables" && exit 1)
 
@@ -98,7 +98,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.deploymentAgentAwsAccessKey }}
           aws-secret-access-key: ${{ secrets.deploymentAgentAwsAccessKeySecret }}
-          aws-region: ${{ env.REGION }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Pull down config settings files
         run: datateer config pull --environment ${{ env.DATATEER_ENV }} --cloud aws
@@ -118,7 +118,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.deploymentAgentAwsAccessKey  }}
           aws-secret-access-key: ${{ secrets.deploymentAgentAwsAccessKeySecret  }}
-          aws-region: ${{ env.REGION }}
+          aws-region: ${{ env.AWS_REGION }}
           aws-security-group-id: ${{ steps.security_group_id_step.outputs.security_group_id }}
           port: "5432"
           to-port: "5432"
@@ -137,7 +137,7 @@ jobs:
             datateer-docker-pipeline-
 
       - name: Deploy pipeline
-        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud aws --region ${{ env.REGION }} --account ${{ env.ACCOUNT }}
+        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud aws --region ${{ env.AWS_REGION }} --account ${{ env.AWS_ACCOUNT_ID }}
         env:
           DEPLOY_KEY_PREFECT_LIB: ${{ secrets.deployKeyPrefectLib }}
           PREFECT__CLOUD__API_KEY: ${{ secrets.deployKeyPrefect }}
diff --git a/.github/workflows/deploy-pipeline-gcp.yml b/.github/workflows/deploy-pipeline-gcp.yml
--- a/.github/workflows/deploy-pipeline-gcp.yml
+++ b/.github/workflows/deploy-pipeline-gcp.yml
@@ -51,16 +51,16 @@ jobs:
         python-version: [3.8]
     name: Build and deploy the pipeline
     env:
-      ACCOUNT: ${{ inputs.gcpProjectId || secrets.GCP_PROJECT_ID }}
-      REGION: ${{ inputs.gcpRegion || secrets.GCP_REGION }}
+      GCP_PROJECT_ID: ${{ inputs.gcpProjectId || secrets.GCP_PROJECT_ID }}
+      GCP_REGION: ${{ inputs.gcpRegion || secrets.GCP_REGION }}
       CLIENT_CODE: ${{ inputs.clientCode || secrets.CLIENT_CODE }}
       DATATEER_ENV: ${{ inputs.environment || 'int' }}
       PIPELINE_NAME: ${{ inputs.pipeline_name || 'main' }}
     steps:
       - name: Prerequisites
         run: |
-          [ -n "${{ env.ACCOUNT }}" ] || (echo "Could not find ACCOUNT in the inputs or in environment variables" && exit 1)
-          [ -n "${{ env.REGION }}" ] || (echo "Could not find REGION in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.GCP_PROJECT_ID }}" ] || (echo "Could not find GCP_PROJECT_ID in the inputs or in environment variables" && exit 1)
+          [ -n "${{ env.GCP_REGION }}" ] || (echo "Could not find GCP_REGION in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.CLIENT_CODE}}" ] || (echo "Could not find CLIENT_CODE in the inputs or in environment variables" && exit 1)
           [ -n "${{ env.DATATEER_ENV }}" ] || (echo "Could not find DATATEER_ENV in the inputs or in environment variables" && exit 1)
 
@@ -118,7 +118,7 @@ jobs:
             datateer-docker-pipeline-
 
       - name: Deploy pipeline
-        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud gcp --region ${{ env.REGION }} --account ${{ env.ACCOUNT }}
+        run: datateer pipeline deploy ${{ env.PIPELINE_NAME }} --environment ${{ env.DATATEER_ENV }} --cloud gcp --region ${{ env.GCP_REGION }} --account ${{ env.GCP_PROJECT_ID }}
         env:
           DEPLOY_KEY_PREFECT_LIB: ${{ secrets.deployKeyPrefectLib }}
           PREFECT__CLOUD__API_KEY: ${{ secrets.deployKeyPrefect }}
